version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'

workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          store_artifacts: true
          record: true
          post-steps:
            - store_test_results:
                path: cypress/results