name: Trigger CircleCi job

on:
  push:
    branches:
      - master

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: $