name: Trigger CircleCi job

on:
  push:
    branches:
      - master

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $